### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by james-anderson** [indiana-university/conduit#103]
Ideally update all dependencies to whatever the current version is, especially RxJS, but certainly whatever the latest version that can be used without major code changes.

**Comment by basham** [comment]
There are a lot of dev dependencies that can be updated. But all the peer dependencies (which include RxJS) just indicate the earliest version that can be supported. I need to test it, but I'm guessing this is still compatible with the latest versions of RxJS and React. Maybe some of the React lifecycle methods are depreciated? Is there anything more specific that you want me to investigate?
