### ISSUE TITLE
Update README to remove peer dependency versions

### ISSUE THREAD

**Issue by james-anderson-iu** [indiana-university/conduit#108]
With the release of `conduit-rxjs@0.6.0` and `conduit-rxjs-react@0.7.0` there was one detail we missed. The READMEs still say to install peer dependencies for React v0.14.0 and RxJS v6.2.0, but the package.json files say React v16.3.0 and RxJS v7.2.0. We should update the READMEs to reflect what is in the package.json files.

**Comment by basham** [comment]
I would be okay with removing the references to particular peer dependency versions in the READMEs. That way, the version numbers are only handled in `package.json`. NPM will complain to users if they install an incompatible peer dependency version. That should be good enough.

**Comment by james-anderson-iu** [comment]
That makes sense to me.
